name: build docker image

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - 'master'

jobs:
  build:
    env: IMAGE_NAME=docker.pkg.github.com/${{ github.repository }}/cyoa-server:${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker built -t $IMAGE_NAME
    - name: docker login
      run: docker login docker.pkg.github.com -u valdemarceccon -p ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      run: run docker push $IMAGE_NAME

