name: build docker image and push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Nome'
        required: true
        default: 'Valdemar'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
      IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/cyoa-server:${{ github.sha }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: docker login 
      run: docker login docker.pkg.github.com -u valdemarceccon -p ${{ secrets.GITHUB_TOKEN }}
    - name: docker build
      run: docker build -t $IMAGE_NAME .
    - name: docker push
      run: docker push $IMAGE_NAME
      
    

    
